linux: &linux
  os: linux
  dist: xenial
  python: "3.7"

osx: &osx
  os: osx
  osx_image: xcode11.3
  language: shell

matrix:
  include:
    - <<: *linux
      name: "Linux"
      env: CC=gcc-9 CXX=g++-9 GCOV=gcov-9
      language: shell
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - gcc-9
            - libstdc++-9-dev

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev-tools
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then (
    wget https://cmake.org/files/LatestRelease/cmake-3.17.0-Linux-x86_64.sh &&
    chmod +x cmake-3.17.0-Linux-x86_64.sh &&
    ./cmake-3.17.0-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
    ); fi
  - cmake --version

script:
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -D BUILD_TESTS=OFF -D CMAKE_C_COMPILER=gcc-9 -D CMAKE_CXX_COMPILER=g++-9 -D CMAKE_BUILD_TYPE=DEBUG ..
  - cmake --build .

notifications:
  on_success: change
  on_failure: always
  on_start: false